#!/bin/bash

source ./runner.sh

# Build tasks
runner_default_task="static"
task_static() {
    hugo
}

task_watch() {
    hugo server || return
}

task_offline() {
    msbuild build.proj /p:OfflineDoc_BuildPdf=true
}

task_optipng() {
    find . -name "*.png" -exec optipng "{}" +
}
