baseurl = "https://fahrplan.manuelhu.de/"
languageCode = "de-de"
title = "FPLedit"
theme = "hugo-material-docs"
defaultContentLanguage = "de"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
disableAliases = true
#navigateToChanged = true

[params]
	author = "Manuel Huber"
	description = "Ein einfaches Programm zum Erstellen von (Buch-)Fahrplänen für Modelleisenbahnen. Kompatibel mit jTrainGraph zu Erstellung von Bildfahrplänen."

	download_url = "/download/"		# URL für Download-Button
	version = "1.4.0"				# Aktuelle Programmversion

	logo = "files/logo.png"			# Seitenlogo
	favicon = "files/favicon.ico"	# Seitenicon

	[params.palette]
    	primary = "light-green"
    	accent  = "lime"

[outputs]
	home = ["HTML"]
	page = ["HTML"]
	section = ["HTML"]

[[menu.main]]
	name   = "Start"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Dokumentation"
	weight = 2
	identifier = "doku"

[[menu.main]]
	name   = "Einführung"
	url    = "einfuehrung/"
	weight = 3
	parent = "doku"

[[menu.main]]
	name   = "Fahrpläne bearbeiten"
	url    = "fahrplaene-bearbeiten/"
	weight = 10
	parent = "doku"

[[menu.main]]
	name   = "Bildfahrpläne"
	url    = "bildfahrplaene/"
	weight = 20
	parent = "doku"

[[menu.main]]
	name   = "Buchfahrpläne"
	url    = "buchfahrplaene/"
	weight = 30
	parent = "doku"

[[menu.main]]
	name   = "Aushangfahrpläne"
	url    = "aushangfahrplaene/"
	weight = 40
	parent = "doku"

[[menu.main]]
	name   = "Impressum"
	url    = "https://manuelhu.de/impressum.html"
	weight = 100