baseurl = "https://fahrplan.manuelhu.de/"
languageCode = "de-de"
title = "Fahrplan"
theme = "hugo-material-docs"

[params]
	# General information
	author = "Manuel Huber"
	description = "Ein simples Programm zum Erstellen von Fahrplänen."
	copyright = "Manuel Huber"

	# Repository
	#provider = "GitHub"
	#repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "wieslauterbahn"
	github  = "ManuelHu"
	email   = "info@manuelhu.de"


[[menu.main]]
	name   = "Fahrplan"
	url    = "/"
	weight = 0
	
[[menu.main]]
	name   = "Fahrpläne bearbeiten"
	url    = "fahrplaene-bearbeiten/"
	weight = 10