baseurl = "https://fahrplan.manuelhu.de/"
languageCode = "de-de"
title = "FPLedit"
theme = "hugo-material-docs"
defaultContentLanguage = "de"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]
disableAliases = true
#navigateToChanged = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
	author = "Made with ❤️ by Manuel Huber"
	description = "Ein einfaches Programm zum Erstellen und Bearbeiten von Fahrplänen für Modelleisenbahnen und anschließendem Export als Buch-, Aushang oder Tabellenfahrplan. Kompatibel mit jTrainGraph zu Erstellung von Bildfahrplänen."

	download_url = "/download/"		# URL für Download-Button
	version = "2.5.0"				# Aktuelle Programmversion

	logo = "files/logo.svg"			# Seitenlogo
	twitter_logo = "files/logo.png" # Logo für Twitter Cards
	favicon = "files/favicon.ico"	# Seitenicon

	[params.palette]
    	primary = "light-green"
    	accent  = "teal"

[outputs]
	home = ["HTML", "LUNR", "mod", "tex"]
	page = ["HTML"]
	section = ["HTML"]

[mediaTypes]
[mediaTypes."text/lunr"]
	suffixes = [ "" ]
	delimiter = ""
[mediaTypes."text/latex"]
	suffixes = [ ".tex" ]
	delimiter = ""

[outputFormats]
[outputFormats.LUNR]
	mediatype = "text/lunr"
	baseName = "lunr_idx.js"
	isPlainText = true
	notAlternative = true
[outputFormats.mod]
	mediaType = "text/html"
	baseName = "offline-idx"
	isHTML = true
	protocol = "mod://"
[outputFormats.tex]
	mediaType = "text/latex"
	baseName = "offline-latex"
	isHTML = false
	protocol = "tex://"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[[menu.main]]
	name   = "Start"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Dokumentation"
	weight = 2
	identifier = "doku"

[[menu.main]]
	name   = "Einführung"
	url    = "einfuehrung/"
	weight = 5
	parent = "doku"

[[menu.main]]
	name   = "Fahrpläne bearbeiten"
	url    = "fahrplaene-bearbeiten/"
	weight = 10
	parent = "doku"
	identifier = "edit"

[[menu.main]]
	name   = "Lineare Strecken"
	url    = "fahrplaene-bearbeiten/linear/"
	weight = 11
	parent = "edit"

[[menu.main]]
	name   = "Netzwerk-Fahrpläne"
	url    = "fahrplaene-bearbeiten/network/"
	weight = 12
	parent = "edit"

[[menu.main]]
	name   = "Fortgeschritten: Zirkuläre Netze"
	url    = "fahrplaene-bearbeiten/cycles/"
	weight = 13
	parent = "edit"

[[menu.main]]
	name   = "Buchfahrpläne"
	url    = "buchfahrplaene/"
	weight = 30
	parent = "doku"

[[menu.main]]
	name   = "Aushangfahrpläne"
	url    = "aushangfahrplaene/"
	weight = 40
	parent = "doku"

[[menu.main]]
	name   = "Kursbuch"
	url    = "tabellenfahrplaene/"
	weight = 50
	parent = "doku"

[[menu.main]]
	name   = "Bildfahrpläne mit jTrainGraph"
	url    = "bildfahrplaene/"
	weight = 60
	parent = "doku"

[[menu.main]]
	name   = "Erweiterbarkeit"
	url    = "erweiterbarkeit/"
	weight = 70
	parent = "doku"

[[menu.main]]
	name   = "Erweiterungen entwickeln"
	url    = "dev/"
	weight = 400

[[menu.main]]
	name   = "Projekt auf GitHub&nbsp;<span class=\"icon icon-github\"></span>"
	url    = "https://github.com/fpledit/fpledit"
	weight = 500

[[menu.main]]
	name   = "Kontakt | Impressum"
	url    = "https://www.manuelhu.de/impressum.html"
	weight = 1000

[[menu.main]]
	name   = "Datenschutzerklärung"
	url    = "https://www.manuelhu.de/datenschutz.html"
	weight = 1010
