baseurl = "https://fahrplan.manuelhu.de/"
languageCode = "de-de"
title = "FPLedit"
theme = "hugo-material-docs"
defaultContentLanguage = "de"
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
disableAliases = true
#navigateToChanged = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
	author = "Manuel Huber"
	description = "Ein einfaches Programm zum Erstellen und Bearbeiten von Buch- und Aushangfahrplänen für Modelleisenbahnen. Kompatibel mit jTrainGraph zu Erstellung von Bildfahrplänen."

	download_url = "/download/"		# URL für Download-Button
	version = "1.5.2"				# Aktuelle Programmversion

	logo = "files/logo.svg"			# Seitenlogo
	twitter_logo = "files/logo.png" # Logo für Twitter Cards
	favicon = "files/favicon.ico"	# Seitenicon

	[params.palette]
    	primary = "light-green"
    	accent  = "teal"

[outputs]
	home = ["HTML", "LUNR"]
	page = ["HTML"]
	section = ["HTML"]


[mediaTypes]
[mediaTypes."text/lunr"]
	suffix = ""
	delimiter = ""

[outputFormats]
[outputFormats.LUNR]
	mediatype = "text/lunr"
	baseName = "lunr_idx.js"
	isPlainText = true
	notAlternative = true

[[menu.main]]
	name   = "Start"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Dokumentation"
	weight = 2
	identifier = "doku"

[[menu.main]]
	name   = "Einführung"
	url    = "einfuehrung/"
	weight = 5
	parent = "doku"

[[menu.main]]
	name   = "Fahrpläne bearbeiten"
	url    = "fahrplaene-bearbeiten/"
	weight = 10
	parent = "doku"

[[menu.main]]
	name   = "Bildfahrpläne"
	url    = "bildfahrplaene/"
	weight = 20
	parent = "doku"

[[menu.main]]
	name   = "Buchfahrpläne"
	url    = "buchfahrplaene/"
	weight = 30
	parent = "doku"

[[menu.main]]
	name   = "Aushangfahrpläne"
	url    = "aushangfahrplaene/"
	weight = 40
	parent = "doku"

[[menu.main]]
	name   = "Kursbuch"
	url    = "tabellenfahrplaene/"
	weight = 50
	parent = "doku"

[[menu.main]]
	name   = "Erweiterungen entwickeln"
	url    = "dev/"
	weight = 60
	parent = "doku"

[[menu.main]]
	name   = "Kontakt | Impressum"
	url    = "https://manuelhu.de/impressum.html"
	weight = 200